### ISSUE TITLE
A question about `getKnownEdges` and `getUnknownEdges`

### ISSUE THREAD

**Issue by winddd** [hengxin/PolySI-PVLDB2023-Artifacts#1]
Hello, thank you all for the interesting work! 
I am reading PolySI's implementation and got several questions. 
From my understanding (correct me if I am wrong), the code snippet below bind the edge variable of the Generalizaed Polygraph to SI graph and gunrantees that they share the same truth value.
```java
var knownEdges = Utils.getKnownEdges(graphA, graphB, matAC);
addConstraints(constraints, graphA, graphB);
var unknownEdges = Utils.getUnknownEdges(graphA, graphB, reachability,
                solver);
...
var addToMonoSAT = ((Consumer<Triple<Transaction<KeyType, ValueType>, Transaction<KeyType, ValueType>, Lit>>) e -> {
    var n = e.getLeft();
    var s = e.getMiddle();

    solver.assertEqual(e.getRight(),
            monoGraph.addEdge(nodeMap.get(n), nodeMap.get(s)));
});

knownEdges.forEach(addToMonoSAT);
unknownEdges.forEach(addToMonoSAT);
```
May I ask why we need to distinguish known edges and unknown edges here? Can we simply follow the pseudocode line 40-44([PolySI paper](https://www.vldb.org/pvldb/vol16/p1264-wei.pdf)), first initialize graphA and graphB with known edges, then add all edges in constraints to known graphA and graphB according to their edge types respectively, and then use three nested loop like `getUnknownEdges` does to retrieve all the known and unknown edges in one go?

**Comment by happy-kai** [comment]
TheThe idea is correct, it can be implemented in this way.

**Comment by happy-kai** [comment]
The idea is correct, and it can be implemented in this way.

**Comment by winddd** [comment]
Thanks for your response.
